# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Lint with flake8
      run: |
        # Install flake8
        pip install flake8
        flake8 .
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag aiodeu:$GITHUB_SHA
    - name: Run tests in docker
      run: |
        docker run \
            -v $(pwd):/app \
            --rm \
            aiodeu:$GITHUB_SHA \
        sh -c 'cd /app && pip install pytest pytest-asyncio moto .[faust,aws] && cythonize -X language_level=3 -a -i aiodeu/cetl.pyx && pytest'
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'aiodeu:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM,LOW'
